# Generated by Django 5.0.2 on 2024-03-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EC',
        ),
        migrations.DeleteModel(
            name='TechnicalFault',
        ),
    ]
