# Generated by Django 5.0.2 on 2024-03-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManagement', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalfault',
            name='location',
            field=models.CharField(choices=[('ITL', 'ITL'), ('ITS', 'ITS'), ('Library', 'Library'), ('NONE', 'None')], max_length=10),
        ),
    ]
