# Generated by Django 5.0.2 on 2024-03-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManagement', '0006_alter_ec_status_update_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec',
            name='status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='technicalfault',
            name='status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
