# Generated by Django 5.0.2 on 2024-04-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManagement', '0007_alter_ec_status_alter_technicalfault_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalfault',
            name='location',
            field=models.CharField(choices=[('ITL', 'ITL'), ('ITS', 'ITS'), ('Library', 'Library'), ('QMplus', 'QMplus'), ('Mysis', 'Mysis'), ('Other', 'Other')], max_length=10),
        ),
    ]
