# Generated by Django 5.0.3 on 2024-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManagement', '0008_alter_technicalfault_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=7),
        ),
        migrations.AddField(
            model_name='technicalfault',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=7),
        ),
    ]
