# Generated by Django 5.0.4 on 2024-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManagement', '0009_ec_priority_technicalfault_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='evidence/'),
        ),
        migrations.AddField(
            model_name='technicalfault',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='evidence/'),
        ),
    ]
