# Generated by Django 5.0.4 on 2024-04-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManagement', '0010_ec_file_technicalfault_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ec',
            old_name='file',
            new_name='evidence',
        ),
        migrations.RenameField(
            model_name='technicalfault',
            old_name='file',
            new_name='evidence',
        ),
    ]
