# Generated by Django 5.0.4 on 2024-04-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManagement', '0011_rename_file_ec_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec',
            name='dateResolved',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='technicalfault',
            name='dateResolved',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
