# Generated by Django 5.0.3 on 2024-04-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
