# Generated by Django 5.0.2 on 2024-03-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serviceStatus',
            fields=[
                ('service_name', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Good Service', 'Good Service'), ('Partial Service', 'Partial Service'), ('No Service', 'No Service')], default='Good Service', max_length=20)),
                ('status_description', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
