# Generated by Django 5.0.2 on 2024-03-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceStatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='status_description',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
