# Generated by Django 5.0.3 on 2024-04-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceStatus', '0002_alter_servicestatus_status_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='status_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
